/**
 * WebServiceStub.java
 *
 * This is just a stub implementation to make the exmaple work.
 * The full web service client implementation would be auto-generated by the Apache Axis client generator or some
 * other tool..
 */

package example;

import java.net.MalformedURLException;
import java.net.URL;

public class WebServiceStub {
	
	private URL wsdlUrl;
	
	public WebServiceStub(String wsdlUrl) {
		try {
			this.wsdlUrl = new URL(wsdlUrl);
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

    public void failIfUnreachable() throws java.rmi.RemoteException {
    	// Check the connection to the web service somehow and throw a RemoteException if there is an issue.
    }

	public void operation0(org.apache.axis.types.UnsignedInt nIntVal1, // Input value
			javax.xml.rpc.holders.IntHolder nIntVal2, // Output value
			javax.xml.rpc.holders.StringHolder sStringVal1) // Output value
					throws java.rmi.RemoteException {
		// here the web service method would be called with the input parameter(s)
		// then some values would be populated to the output parameters
		nIntVal2.value = 0;
		sStringVal1.value = "opertion 0 complete";
    }

	public void operation1(org.apache.axis.types.UnsignedInt nIntVal2, // Input value
			javax.xml.rpc.holders.IntHolder nIntVal3, // Output value
			javax.xml.rpc.holders.StringHolder sStringVal2) // Output value
					throws java.rmi.RemoteException {
		// here the web service method would be called with the input parameter(s)
		// then some values would be populated to the output parameters
		nIntVal3.value = 1;
		sStringVal2.value = "opertion 1 complete";
    }
	public void operation2(org.apache.axis.types.UnsignedInt nIntVal3, // Input value
			javax.xml.rpc.holders.IntHolder nIntVal4, // Output value
			javax.xml.rpc.holders.StringHolder sStringVal3) // Output value
					throws java.rmi.RemoteException {
		// here the web service method would be called with the input parameter(s)
		// then some values would be populated to the output parameters
		nIntVal4.value = 2;
		sStringVal3.value = "opertion 2 complete";
    }
	public void operation3(org.apache.axis.types.UnsignedInt nIntVal4, // Input value
			javax.xml.rpc.holders.IntHolder nIntVal1, // Output value
			javax.xml.rpc.holders.StringHolder sStringVal4) // Output value
					throws java.rmi.RemoteException {
		// here the web service method would be called with the input parameter(s)
		// then some values would be populated to the output parameters
		nIntVal1.value = 3;
		sStringVal4.value = "opertion 3 complete";
    }
	public void operation4(org.apache.axis.types.UnsignedInt nIntVal1, // Input value
			javax.xml.rpc.holders.IntHolder nIntVal2, // Output value
			javax.xml.rpc.holders.StringHolder sStringVal1) // Output value
					throws java.rmi.RemoteException {
		// here the web service method would be called with the input parameter(s)
		// then some values would be populated to the output parameters
		nIntVal2.value = 4;
		sStringVal1.value = "opertion 4 complete";
    }
}
